import type { Metadata } from "next";
import './globals.css';
import { THEME_TYPES } from '@/app/lib/constants';
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Guitaraptor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={THEME_TYPES.THEME_LIGHT}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
