
import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: "Guitaraptor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
          {children}
      </body>
    </html>
  );
}
